path: /home/hatsu/coding/CapProj/TestSeg_1/dataset_2
train: /home/hatsu/coding/CapProj/TestSeg_1/dataset_2/images/train
val: /home/hatsu/coding/CapProj/TestSeg_1/dataset_2/images/val

nc: 1
names: ['Fighter']
