path: /home/hatsu/coding/CapProj/TestSeg_1/dataset_4
train: /home/hatsu/coding/CapProj/TestSeg_1/dataset_4/images/train
val: /home/hatsu/coding/CapProj/TestSeg_1/dataset_4/images/val

nc: 1
names: ['Fighter']
